
package se.yrgo.dataaccess;

import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;

import se.yrgo.domain.*;

public class CustomerDaoJdbcTemplateImpl implements CustomerDao {
    private static final String DELETE_SQL = "DELETE FROM Customers WHERE customer_id=?";
    private static final String UPDATE_SQL = "UPDATE Customers SET company_name=?, email=?, telephone=?, notes=? WHERE customer_id=?";
    private static final String INSERT_SQL = "INSERT INTO Customers (customer_id, company_name, email, telephone, notes) VALUES (?,?,?,?,?)";
    private static final String GET_CUSTOMER_SQL = "SELECT * FROM Customers WHERE customer_id=?";
    private static final String GET_ALL_CUSTOMERS_SQL = "SELECT * FROM Customers";
    private static final String GET_CUSTOMER_BY_NAME_SQL = "SELECT * FROM Customers WHERE company_name=?";
    private static final String GET_CUSTOMER_CALLS_SQL = "SELECT * FROM Calls WHERE customer_id=?";
    private static final String ADD_CALL_SQL = "INSERT INTO Calls (time_and_date, notes, customer_id) VALUES (?,?,?)";

    private JdbcTemplate template;

    public CustomerDaoJdbcTemplateImpl(JdbcTemplate template) {
        this.template = template;
        createTables();
    }

    /*
     * private void createTables() {
     * try{
     * this.template.
     * update("CREATE TABLE ACTION (ACTION_ID integer generated by default as identity (start with 1), DETAILS VARCHAR(255), COMPLETE BOOLEAN, OWNING_USER VARCHAR(20), REQUIRED_BY DATE)"
     * );
     * }catch (org.springframework.jdbc.BadSqlGrammarException e){
     * System.out.println("Assuming the Action table exists");
     * }
     * }
     */

    private void createTables() {
        this.template.update("""
                DROP TABLE IF EXISTS Calls
                """);
                
        this.template.update("""
                DROP TABLE IF EXISTS Customers
                """);

        this.template.update("""
                CREATE TABLE IF NOT EXISTS Customers(
                    customer_id VARCHAR(7) PRIMARY KEY,
                    company_name VARCHAR(50) NOT NULL,
                    email VARCHAR(100),
                    telephone VARCHAR(50),
                    notes VARCHAR(100) NOT NULL
                )
                """);
        this.template.update("""
                CREATE TABLE IF NOT EXISTS Calls(
                    call_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
                    time_and_date TIMESTAMP NOT NULL,
                    notes VARCHAR(100) NOT NULL,
                    customer_id VARCHAR(7),
                    CONSTRAINT FK_CALLS_CUSTOMERS
                        FOREIGN KEY(customer_id) REFERENCES Customers(customer_id)
                )
                """);
    }

    public void create(Customer newCustomer) {
        this.template.update(INSERT_SQL, newCustomer.getCustomerId(), newCustomer.getCompanyName(),
                newCustomer.getEmail(),
                newCustomer.getTelephone(), newCustomer.getNotes());
    }

    @Override
    public Customer getById(String customerId) throws RecordNotFoundException {
        return this.template.queryForObject(GET_CUSTOMER_SQL, new CustomerRowMapper(), customerId);
    }

    @Override
    public List<Customer> getByName(String name) {
        return this.template.query(GET_CUSTOMER_BY_NAME_SQL, new CustomerRowMapper(), name);
    }

    @Override
    public void update(Customer customerToUpdate) throws RecordNotFoundException {
        this.template.update(UPDATE_SQL,
                customerToUpdate.getCompanyName(),
                customerToUpdate.getEmail(),
                customerToUpdate.getTelephone(),
                customerToUpdate.getNotes(),
                customerToUpdate.getCustomerId());
    }

    @Override
    public void delete(Customer oldCustomer) throws RecordNotFoundException {
        this.template.update(DELETE_SQL, oldCustomer.getCustomerId());
    }

    @Override
    public List<Customer> getAllCustomers() {
        return this.template.query(GET_ALL_CUSTOMERS_SQL, new CustomerRowMapper());
    }

    @Override
    public Customer getFullCustomerDetail(String customerId) throws RecordNotFoundException {
        Customer customer = this.template.queryForObject(GET_CUSTOMER_SQL, new CustomerRowMapper(), customerId);
        List<Call> calls = this.template.query(GET_CUSTOMER_CALLS_SQL, new CallRowMapper(), customerId);
        customer.setCalls(calls);
        return customer;
    }

    @Override
    public void addCall(Call newCall, String customerId) throws RecordNotFoundException {
        this.template.update(ADD_CALL_SQL, newCall.getTimeAndDate(), newCall.getNotes(), customerId);
    }

    /*
     * private void createTables() {
     * try{
     * this.template.
     * update("CREATE TABLE ACTION (ACTION_ID integer generated by default as identity (start with 1), DETAILS VARCHAR(255), COMPLETE BOOLEAN, OWNING_USER VARCHAR(20), REQUIRED_BY DATE)"
     * );
     * }catch (org.springframework.jdbc.BadSqlGrammarException e){
     * System.out.println("Assuming the Action table exists");
     * }
     * }
     * 
     * public List<Action> getIncompleteActions(String userId) {
     * return this.template.query(GET_INCOMPLETE_SQL, new ActionRowMapper(), userId,
     * false);
     * }
     * 
     * public void update(Action actionToUpdate) throws RecordNotFoundException {
     * this.template.update(UPDATE_SQL,actionToUpdate.getDetails(),actionToUpdate.
     * isComplete(), actionToUpdate.getOwningUser(),
     * actionToUpdate.getRequiredBy().getTime(), actionToUpdate.getActionId() );
     * }
     * 
     * public void delete(Action oldAction) throws RecordNotFoundException {
     * this.template.update(DELETE_SQL, oldAction.getActionId());
     * }
     * }
     * 
     * /*
     * class ActionRowMapper implements RowMapper<Action> {
     * public Action mapRow(ResultSet rs, int arg1) throws SQLException {
     * int actionId = rs.getInt(1);
     * String details = rs.getString(2);
     * boolean complete = rs.getBoolean(3);
     * String owningUser = rs.getString(4);
     * Date requiredBy = rs.getDate(5);
     * 
     * Calendar requiredByCal = new java.util.GregorianCalendar();
     * requiredByCal.setTime(requiredBy);
     * 
     * return new Action("" + actionId, details, requiredByCal, owningUser,
     * complete);
     * }
     */

}

class CustomerRowMapper implements RowMapper<Customer> {
    public Customer mapRow(ResultSet rs, int arg1) throws SQLException {
        String customerId = rs.getString(1);
        String companyName = rs.getString(2);
        String email = rs.getString(3);
        String telephone = rs.getString(4);
        String notes = rs.getString(5);

        return new Customer(customerId, companyName, email, telephone,
                notes);
    }
}

class CallRowMapper implements RowMapper<Call> {
    public Call mapRow(ResultSet rs, int arg1) throws SQLException {
        Date dateAndTime = rs.getDate(2);
        String notes = rs.getString(3);

        return new Call(notes, dateAndTime);
    }
}